default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitterclone_development

test:
  <<: *default
  database: twitterclone_test

production:
  <<: *default
  database: twitterclone_production
  username: twitterclone
  password: <%= ENV['TWITTERCLONE_DATABASE_PASSWORD'] %>
